name: Jsdoc

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./scripts
          output_dir: ./docs
          config_file: conf.json
          template: minami
          front_page: README.md

      - name: Copy static files
        run: |
          cp ./LICENSE ./docs/
          cp ./README.md ./docs/
          cp -r ./resources/ ./docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ github.event.head_commit.message }}
